Fixed errors for the install_http function

diff --git a/setmyenv b/setmyenv
--- a/setmyenv
+++ b/setmyenv
@@ -9,12 +9,13 @@
 #
 
 dir_tmp="./tmp"
+dir_iso="/mnt/iso"
 
 to_install_apt_dev=('build-essential' 'git' 'subversion' 'python3' 'python3-pip' 'python3-dev' 'python-virtualenv' 'gdb')
 to_install_apt_fware=('firmware-ralink' 'firmware-linux-nonfree') 
 to_install_apt_misc=('gimp' 'irssi' 'brasero')
 to_install_apt_sec=('tor' 'proxychains' 'nmap' 'wireshark' 'libimage-exiftool-perl')
-to_install_apt_sys=('vim' 'pm-utils' 'unrar' 'deborphan' 'software-properties-common' 'htop' 'terminator' 'curl' 'ssh' 'virtualbox' 'virtualbox-guest-additions-iso')
+to_install_apt_sys=('wine' 'vim' 'pm-utils' 'unrar' 'deborphan' 'software-properties-common' 'htop' 'terminator' 'curl' 'ssh' 'virtualbox' 'virtualbox-guest-additions-iso')
 to_install_apt=(${to_install_apt_dev[@]} ${to_install_apt_fware[@]} ${to_install_apt_misc[@]} ${to_install_apt_sec[@]} ${to_install_apt_sys[@]})
 declare -A to_install_http
 to_install_http=(["skype"]="http://www.skype.com/go/getskype-linux-deb" ["pycharm"]="https://download.jetbrains.com/python/pycharm-community-5.0.3.tar.gz" ["subl"]="https://download.sublimetext.com/sublime-text_build-3083_amd64.deb" ["teamviewer"]="http://download.teamviewer.com/download/teamviewer_i386.deb")
@@ -50,10 +51,10 @@ function install_http() {
 	    echo -e "  + $i is not installed; installation in progress..."
             file_name=$i-install
 	    wget -q -O $dir_tmp/$file_name ${to_install_http[$i]}
-            file_type=$(file $dir_tmp/$file_name | grep -c "Debian binary package" && echo "deb" || echo "")
+            file_type=$(file $dir_tmp/$file_name | grep -c "Debian binary package" && echo "deb" || echo "other")
             file_type=$(echo $file_type | cut -d" " -f2)
-            if [ $file_type = "" ]; then
-                file_type=$(file $dir_tmp/$file_name | grep -c "gzip compressed data, from FAT filesystem" && echo "tar.gz" || echo "")
+            if [ $file_type = "other" ]; then
+                file_type=$(file $dir_tmp/$file_name | grep -c "gzip compressed data, from FAT filesystem" && echo "tar.gz" || echo "other")
                 file_type=$(echo $file_type | cut -d" " -f2)
             fi
             mv $dir_tmp/$file_name $dir_tmp/$file_name.$file_type
@@ -61,8 +62,11 @@ function install_http() {
                 sudo dpkg -i $dir_tmp/$file_name.$file_type
             elif [ $file_type = "tar.gz" ]; then
                 sudo tar xzvf $dir_tmp/$file_name.$file_type -C /opt/ 
+                ls /opt/
                 elem=$(ls /opt/ | grep $i)
                 sudo ln -s /opt/$elem/bin/$i.sh /usr/bin/$i
+            else
+                echo "##ERROR: Unsupported file type!"
             fi
 	    sudo apt-get -f install
 	fi
@@ -126,3 +130,6 @@ rm -R $dir_tmp
 
 echo -e "\n## Uninstalling unuseful APT packages"
 uninstall_apt
+
+echo -e "\n## Creating the 'iso' dir"
+sudo mkdir $dir_iso
